version: "2"

linters:
  default: none
  enable:
    # 基础检查
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

    # 风格
    - revive
    - unconvert
    - gocritic

    # 安全
    - gosec

    # 并发
    - bodyclose
    - noctx
  settings:
    gosec:
      excludes:
        - G115
    revive:
      rules:
        # Enforce GoDoc comments for exported identifiers.
        - name: exported
        - name: unused-parameter
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - noctx
      # Don't require GoDoc comments in *_test.go.
      - path: _test\.go
        linters:
          - revive
        text: "exported (.+) should have comment"
      - path: _test\.go
        linters:
          - gosec
        text: "G402:"
      - path: _test\.go
        linters:
          - gosec
        text: "G104:"
      - path: _test\.go
        linters:
          - revive
        text: "unused-parameter:"
      - path: example/
        linters:
          - revive
        text: "unused-parameter:"
      - path: example/
        linters:
          - errcheck
          - noctx
          - unused

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
