// Copyright 2024 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: error-handling/reason.proto

package error_handling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reason int32

const (
	// Default unspecified error
	Reason_ERROR_REASON_UNSPECIFIED Reason = 0
	// User errors (4xx)
	Reason_USER_NOT_FOUND       Reason = 10
	Reason_INVALID_CREDENTIALS  Reason = 11
	Reason_INVALID_INPUT        Reason = 12
	Reason_EMAIL_ALREADY_EXISTS Reason = 13
	// Resource errors (4xx)
	Reason_BOOK_NOT_FOUND        Reason = 20
	Reason_SHELF_NOT_FOUND       Reason = 21
	Reason_BOOK_ALREADY_BORROWED Reason = 22
	Reason_SHELF_FULL            Reason = 23
	// System errors (5xx)
	Reason_INTERNAL_ERROR Reason = 100
	Reason_DATABASE_ERROR Reason = 101
	Reason_NETWORK_ERROR  Reason = 102
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0:   "ERROR_REASON_UNSPECIFIED",
		10:  "USER_NOT_FOUND",
		11:  "INVALID_CREDENTIALS",
		12:  "INVALID_INPUT",
		13:  "EMAIL_ALREADY_EXISTS",
		20:  "BOOK_NOT_FOUND",
		21:  "SHELF_NOT_FOUND",
		22:  "BOOK_ALREADY_BORROWED",
		23:  "SHELF_FULL",
		100: "INTERNAL_ERROR",
		101: "DATABASE_ERROR",
		102: "NETWORK_ERROR",
	}
	Reason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"USER_NOT_FOUND":           10,
		"INVALID_CREDENTIALS":      11,
		"INVALID_INPUT":            12,
		"EMAIL_ALREADY_EXISTS":     13,
		"BOOK_NOT_FOUND":           20,
		"SHELF_NOT_FOUND":          21,
		"BOOK_ALREADY_BORROWED":    22,
		"SHELF_FULL":               23,
		"INTERNAL_ERROR":           100,
		"DATABASE_ERROR":           101,
		"NETWORK_ERROR":            102,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_handling_reason_proto_enumTypes[0].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_error_handling_reason_proto_enumTypes[0]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_error_handling_reason_proto_rawDescGZIP(), []int{0}
}

var File_error_handling_reason_proto protoreflect.FileDescriptor

const file_error_handling_reason_proto_rawDesc = "" +
	"\n" +
	"\x1berror-handling/reason.proto\x12.codesjoy.yggdrasil.example.proto.errorhandling\x1a\x1fcodesjoy/reason/v1/reason.proto*\xcc\x02\n" +
	"\x06Reason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x0eUSER_NOT_FOUND\x10\n" +
	"\x1a\x03\xa8E\x05\x12\x1c\n" +
	"\x13INVALID_CREDENTIALS\x10\v\x1a\x03\xa8E\x10\x12\x16\n" +
	"\rINVALID_INPUT\x10\f\x1a\x03\xa8E\x03\x12\x1d\n" +
	"\x14EMAIL_ALREADY_EXISTS\x10\r\x1a\x03\xa8E\x06\x12\x17\n" +
	"\x0eBOOK_NOT_FOUND\x10\x14\x1a\x03\xa8E\x05\x12\x18\n" +
	"\x0fSHELF_NOT_FOUND\x10\x15\x1a\x03\xa8E\x05\x12\x1e\n" +
	"\x15BOOK_ALREADY_BORROWED\x10\x16\x1a\x03\xa8E\t\x12\x13\n" +
	"\n" +
	"SHELF_FULL\x10\x17\x1a\x03\xa8E\b\x12\x17\n" +
	"\x0eINTERNAL_ERROR\x10d\x1a\x03\xa8E\r\x12\x17\n" +
	"\x0eDATABASE_ERROR\x10e\x1a\x03\xa8E\x0e\x12\x16\n" +
	"\rNETWORK_ERROR\x10f\x1a\x03\xa8E\x0e\x1a\x04\xa0E\xf4\x03B\xba\x02\n" +
	"2com.codesjoy.yggdrasil.example.proto.errorhandlingB\vReasonProtoP\x01Z\x19github.com/error-handling\xa2\x02\x05CYEPE\xaa\x02.Codesjoy.Yggdrasil.Example.Proto.Errorhandling\xca\x02.Codesjoy\\Yggdrasil\\Example\\Proto\\Errorhandling\xe2\x02:Codesjoy\\Yggdrasil\\Example\\Proto\\Errorhandling\\GPBMetadata\xea\x022Codesjoy::Yggdrasil::Example::Proto::Errorhandlingb\x06proto3"

var (
	file_error_handling_reason_proto_rawDescOnce sync.Once
	file_error_handling_reason_proto_rawDescData []byte
)

func file_error_handling_reason_proto_rawDescGZIP() []byte {
	file_error_handling_reason_proto_rawDescOnce.Do(func() {
		file_error_handling_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_handling_reason_proto_rawDesc), len(file_error_handling_reason_proto_rawDesc)))
	})
	return file_error_handling_reason_proto_rawDescData
}

var file_error_handling_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_handling_reason_proto_goTypes = []any{
	(Reason)(0), // 0: codesjoy.yggdrasil.example.proto.errorhandling.Reason
}
var file_error_handling_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_handling_reason_proto_init() }
func file_error_handling_reason_proto_init() {
	if File_error_handling_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_handling_reason_proto_rawDesc), len(file_error_handling_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_handling_reason_proto_goTypes,
		DependencyIndexes: file_error_handling_reason_proto_depIdxs,
		EnumInfos:         file_error_handling_reason_proto_enumTypes,
	}.Build()
	File_error_handling_reason_proto = out.File
	file_error_handling_reason_proto_goTypes = nil
	file_error_handling_reason_proto_depIdxs = nil
}
