// Code generated by protoc-gen-codesjoy-reason. DO NOT EDIT.

package error_handling

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the reason plugin package it is being compiled against.

var Reason_code = map[int32]code.Code{
	0:   code.Code_UNKNOWN,
	10:  code.Code_NOT_FOUND,
	11:  code.Code_UNAUTHENTICATED,
	12:  code.Code_INVALID_ARGUMENT,
	13:  code.Code_ALREADY_EXISTS,
	20:  code.Code_NOT_FOUND,
	21:  code.Code_NOT_FOUND,
	22:  code.Code_FAILED_PRECONDITION,
	23:  code.Code_RESOURCE_EXHAUSTED,
	100: code.Code_INTERNAL,
	101: code.Code_UNAVAILABLE,
	102: code.Code_UNAVAILABLE,
}

func (r Reason) Reason() string {
	return Reason_name[int32(r)]
}

func (r Reason) Domain() string {
	return "codesjoy.yggdrasil.example.proto.errorhandling"
}

func (r Reason) Code() code.Code {
	return Reason_code[int32(r)]
}
