// Copyright 2024 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: error-handling/service.proto

package error_handling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definitions
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_error_handling_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_error_handling_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_error_handling_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_error_handling_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthenticateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserRequest) Reset() {
	*x = AuthenticateUserRequest{}
	mi := &file_error_handling_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserRequest) ProtoMessage() {}

func (x *AuthenticateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateUserResponse) Reset() {
	*x = AuthenticateUserResponse{}
	mi := &file_error_handling_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateUserResponse) ProtoMessage() {}

func (x *AuthenticateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateUserResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthenticateUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_error_handling_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_error_handling_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_error_handling_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_error_handling_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type BorrowBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowBookRequest) Reset() {
	*x = BorrowBookRequest{}
	mi := &file_error_handling_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowBookRequest) ProtoMessage() {}

func (x *BorrowBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowBookRequest.ProtoReflect.Descriptor instead.
func (*BorrowBookRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{10}
}

func (x *BorrowBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BorrowBookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BorrowBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowBookResponse) Reset() {
	*x = BorrowBookResponse{}
	mi := &file_error_handling_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowBookResponse) ProtoMessage() {}

func (x *BorrowBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowBookResponse.ProtoReflect.Descriptor instead.
func (*BorrowBookResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{11}
}

func (x *BorrowBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReturnBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnBookRequest) Reset() {
	*x = ReturnBookRequest{}
	mi := &file_error_handling_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnBookRequest) ProtoMessage() {}

func (x *ReturnBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnBookRequest.ProtoReflect.Descriptor instead.
func (*ReturnBookRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReturnBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ReturnBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnBookResponse) Reset() {
	*x = ReturnBookResponse{}
	mi := &file_error_handling_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnBookResponse) ProtoMessage() {}

func (x *ReturnBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnBookResponse.ProtoReflect.Descriptor instead.
func (*ReturnBookResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReturnBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_error_handling_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{14}
}

func (x *CreateShelfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateShelfRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateShelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfResponse) Reset() {
	*x = CreateShelfResponse{}
	mi := &file_error_handling_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfResponse) ProtoMessage() {}

func (x *CreateShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfResponse.ProtoReflect.Descriptor instead.
func (*CreateShelfResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateShelfResponse) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

type AddBookToShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShelfId       string                 `protobuf:"bytes,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookToShelfRequest) Reset() {
	*x = AddBookToShelfRequest{}
	mi := &file_error_handling_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookToShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookToShelfRequest) ProtoMessage() {}

func (x *AddBookToShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookToShelfRequest.ProtoReflect.Descriptor instead.
func (*AddBookToShelfRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{16}
}

func (x *AddBookToShelfRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

func (x *AddBookToShelfRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type AddBookToShelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBookToShelfResponse) Reset() {
	*x = AddBookToShelfResponse{}
	mi := &file_error_handling_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBookToShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookToShelfResponse) ProtoMessage() {}

func (x *AddBookToShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookToShelfResponse.ProtoReflect.Descriptor instead.
func (*AddBookToShelfResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{17}
}

func (x *AddBookToShelfResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TriggerErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorType     string                 `protobuf:"bytes,1,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"` // "database_error", "network_error", "internal_error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerErrorRequest) Reset() {
	*x = TriggerErrorRequest{}
	mi := &file_error_handling_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerErrorRequest) ProtoMessage() {}

func (x *TriggerErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerErrorRequest.ProtoReflect.Descriptor instead.
func (*TriggerErrorRequest) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{18}
}

func (x *TriggerErrorRequest) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

type TriggerErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerErrorResponse) Reset() {
	*x = TriggerErrorResponse{}
	mi := &file_error_handling_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerErrorResponse) ProtoMessage() {}

func (x *TriggerErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerErrorResponse.ProtoReflect.Descriptor instead.
func (*TriggerErrorResponse) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{19}
}

func (x *TriggerErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Data models
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_error_handling_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{20}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	BorrowerId    string                 `protobuf:"bytes,5,opt,name=borrower_id,json=borrowerId,proto3" json:"borrower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_error_handling_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{21}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetBorrowerId() string {
	if x != nil {
		return x.BorrowerId
	}
	return ""
}

type Shelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CurrentCount  int32                  `protobuf:"varint,4,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_error_handling_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_error_handling_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_error_handling_service_proto_rawDescGZIP(), []int{22}
}

func (x *Shelf) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shelf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shelf) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Shelf) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

var File_error_handling_service_proto protoreflect.FileDescriptor

const file_error_handling_service_proto_rawDesc = "" +
	"\n" +
	"\x1cerror-handling/service.proto\x12.codesjoy.yggdrasil.example.proto.errorhandling\x1a\x1berror-handling/reason.proto\"Y\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"^\n" +
	"\x12CreateUserResponse\x12H\n" +
	"\x04user\x18\x01 \x01(\v24.codesjoy.yggdrasil.example.proto.errorhandling.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"[\n" +
	"\x0fGetUserResponse\x12H\n" +
	"\x04user\x18\x01 \x01(\v24.codesjoy.yggdrasil.example.proto.errorhandling.UserR\x04user\"K\n" +
	"\x17AuthenticateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"z\n" +
	"\x18AuthenticateUserResponse\x12H\n" +
	"\x04user\x18\x01 \x01(\v24.codesjoy.yggdrasil.example.proto.errorhandling.UserR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"U\n" +
	"\x11CreateBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x03 \x01(\tR\x04isbn\"^\n" +
	"\x12CreateBookResponse\x12H\n" +
	"\x04book\x18\x01 \x01(\v24.codesjoy.yggdrasil.example.proto.errorhandling.BookR\x04book\")\n" +
	"\x0eGetBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"[\n" +
	"\x0fGetBookResponse\x12H\n" +
	"\x04book\x18\x01 \x01(\v24.codesjoy.yggdrasil.example.proto.errorhandling.BookR\x04book\"E\n" +
	"\x11BorrowBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12BorrowBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11ReturnBookRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\".\n" +
	"\x12ReturnBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x12CreateShelfRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\"b\n" +
	"\x13CreateShelfResponse\x12K\n" +
	"\x05shelf\x18\x01 \x01(\v25.codesjoy.yggdrasil.example.proto.errorhandling.ShelfR\x05shelf\"K\n" +
	"\x15AddBookToShelfRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\tR\ashelfId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"2\n" +
	"\x16AddBookToShelfResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x13TriggerErrorRequest\x12\x1d\n" +
	"\n" +
	"error_type\x18\x01 \x01(\tR\terrorType\"0\n" +
	"\x14TriggerErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"y\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x04 \x01(\tR\x04isbn\x12\x1f\n" +
	"\vborrower_id\x18\x05 \x01(\tR\n" +
	"borrowerId\"l\n" +
	"\x05Shelf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12#\n" +
	"\rcurrent_count\x18\x04 \x01(\x05R\fcurrentCount2\x81\f\n" +
	"\x0eLibraryService\x12\x93\x01\n" +
	"\n" +
	"CreateUser\x12A.codesjoy.yggdrasil.example.proto.errorhandling.CreateUserRequest\x1aB.codesjoy.yggdrasil.example.proto.errorhandling.CreateUserResponse\x12\x8a\x01\n" +
	"\aGetUser\x12>.codesjoy.yggdrasil.example.proto.errorhandling.GetUserRequest\x1a?.codesjoy.yggdrasil.example.proto.errorhandling.GetUserResponse\x12\xa5\x01\n" +
	"\x10AuthenticateUser\x12G.codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserRequest\x1aH.codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserResponse\x12\x93\x01\n" +
	"\n" +
	"CreateBook\x12A.codesjoy.yggdrasil.example.proto.errorhandling.CreateBookRequest\x1aB.codesjoy.yggdrasil.example.proto.errorhandling.CreateBookResponse\x12\x8a\x01\n" +
	"\aGetBook\x12>.codesjoy.yggdrasil.example.proto.errorhandling.GetBookRequest\x1a?.codesjoy.yggdrasil.example.proto.errorhandling.GetBookResponse\x12\x93\x01\n" +
	"\n" +
	"BorrowBook\x12A.codesjoy.yggdrasil.example.proto.errorhandling.BorrowBookRequest\x1aB.codesjoy.yggdrasil.example.proto.errorhandling.BorrowBookResponse\x12\x93\x01\n" +
	"\n" +
	"ReturnBook\x12A.codesjoy.yggdrasil.example.proto.errorhandling.ReturnBookRequest\x1aB.codesjoy.yggdrasil.example.proto.errorhandling.ReturnBookResponse\x12\x96\x01\n" +
	"\vCreateShelf\x12B.codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfRequest\x1aC.codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfResponse\x12\x9f\x01\n" +
	"\x0eAddBookToShelf\x12E.codesjoy.yggdrasil.example.proto.errorhandling.AddBookToShelfRequest\x1aF.codesjoy.yggdrasil.example.proto.errorhandling.AddBookToShelfResponse\x12\x99\x01\n" +
	"\fTriggerError\x12C.codesjoy.yggdrasil.example.proto.errorhandling.TriggerErrorRequest\x1aD.codesjoy.yggdrasil.example.proto.errorhandling.TriggerErrorResponseB\xbb\x02\n" +
	"2com.codesjoy.yggdrasil.example.proto.errorhandlingB\fServiceProtoP\x01Z\x19github.com/error-handling\xa2\x02\x05CYEPE\xaa\x02.Codesjoy.Yggdrasil.Example.Proto.Errorhandling\xca\x02.Codesjoy\\Yggdrasil\\Example\\Proto\\Errorhandling\xe2\x02:Codesjoy\\Yggdrasil\\Example\\Proto\\Errorhandling\\GPBMetadata\xea\x022Codesjoy::Yggdrasil::Example::Proto::Errorhandlingb\x06proto3"

var (
	file_error_handling_service_proto_rawDescOnce sync.Once
	file_error_handling_service_proto_rawDescData []byte
)

func file_error_handling_service_proto_rawDescGZIP() []byte {
	file_error_handling_service_proto_rawDescOnce.Do(func() {
		file_error_handling_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_handling_service_proto_rawDesc), len(file_error_handling_service_proto_rawDesc)))
	})
	return file_error_handling_service_proto_rawDescData
}

var file_error_handling_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_error_handling_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: codesjoy.yggdrasil.example.proto.errorhandling.CreateUserRequest
	(*CreateUserResponse)(nil),       // 1: codesjoy.yggdrasil.example.proto.errorhandling.CreateUserResponse
	(*GetUserRequest)(nil),           // 2: codesjoy.yggdrasil.example.proto.errorhandling.GetUserRequest
	(*GetUserResponse)(nil),          // 3: codesjoy.yggdrasil.example.proto.errorhandling.GetUserResponse
	(*AuthenticateUserRequest)(nil),  // 4: codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserRequest
	(*AuthenticateUserResponse)(nil), // 5: codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserResponse
	(*CreateBookRequest)(nil),        // 6: codesjoy.yggdrasil.example.proto.errorhandling.CreateBookRequest
	(*CreateBookResponse)(nil),       // 7: codesjoy.yggdrasil.example.proto.errorhandling.CreateBookResponse
	(*GetBookRequest)(nil),           // 8: codesjoy.yggdrasil.example.proto.errorhandling.GetBookRequest
	(*GetBookResponse)(nil),          // 9: codesjoy.yggdrasil.example.proto.errorhandling.GetBookResponse
	(*BorrowBookRequest)(nil),        // 10: codesjoy.yggdrasil.example.proto.errorhandling.BorrowBookRequest
	(*BorrowBookResponse)(nil),       // 11: codesjoy.yggdrasil.example.proto.errorhandling.BorrowBookResponse
	(*ReturnBookRequest)(nil),        // 12: codesjoy.yggdrasil.example.proto.errorhandling.ReturnBookRequest
	(*ReturnBookResponse)(nil),       // 13: codesjoy.yggdrasil.example.proto.errorhandling.ReturnBookResponse
	(*CreateShelfRequest)(nil),       // 14: codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfRequest
	(*CreateShelfResponse)(nil),      // 15: codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfResponse
	(*AddBookToShelfRequest)(nil),    // 16: codesjoy.yggdrasil.example.proto.errorhandling.AddBookToShelfRequest
	(*AddBookToShelfResponse)(nil),   // 17: codesjoy.yggdrasil.example.proto.errorhandling.AddBookToShelfResponse
	(*TriggerErrorRequest)(nil),      // 18: codesjoy.yggdrasil.example.proto.errorhandling.TriggerErrorRequest
	(*TriggerErrorResponse)(nil),     // 19: codesjoy.yggdrasil.example.proto.errorhandling.TriggerErrorResponse
	(*User)(nil),                     // 20: codesjoy.yggdrasil.example.proto.errorhandling.User
	(*Book)(nil),                     // 21: codesjoy.yggdrasil.example.proto.errorhandling.Book
	(*Shelf)(nil),                    // 22: codesjoy.yggdrasil.example.proto.errorhandling.Shelf
}
var file_error_handling_service_proto_depIdxs = []int32{
	20, // 0: codesjoy.yggdrasil.example.proto.errorhandling.CreateUserResponse.user:type_name -> codesjoy.yggdrasil.example.proto.errorhandling.User
	20, // 1: codesjoy.yggdrasil.example.proto.errorhandling.GetUserResponse.user:type_name -> codesjoy.yggdrasil.example.proto.errorhandling.User
	20, // 2: codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserResponse.user:type_name -> codesjoy.yggdrasil.example.proto.errorhandling.User
	21, // 3: codesjoy.yggdrasil.example.proto.errorhandling.CreateBookResponse.book:type_name -> codesjoy.yggdrasil.example.proto.errorhandling.Book
	21, // 4: codesjoy.yggdrasil.example.proto.errorhandling.GetBookResponse.book:type_name -> codesjoy.yggdrasil.example.proto.errorhandling.Book
	22, // 5: codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfResponse.shelf:type_name -> codesjoy.yggdrasil.example.proto.errorhandling.Shelf
	0,  // 6: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.CreateUser:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.CreateUserRequest
	2,  // 7: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.GetUser:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.GetUserRequest
	4,  // 8: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.AuthenticateUser:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserRequest
	6,  // 9: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.CreateBook:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.CreateBookRequest
	8,  // 10: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.GetBook:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.GetBookRequest
	10, // 11: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.BorrowBook:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.BorrowBookRequest
	12, // 12: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.ReturnBook:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.ReturnBookRequest
	14, // 13: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.CreateShelf:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfRequest
	16, // 14: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.AddBookToShelf:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.AddBookToShelfRequest
	18, // 15: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.TriggerError:input_type -> codesjoy.yggdrasil.example.proto.errorhandling.TriggerErrorRequest
	1,  // 16: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.CreateUser:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.CreateUserResponse
	3,  // 17: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.GetUser:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.GetUserResponse
	5,  // 18: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.AuthenticateUser:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.AuthenticateUserResponse
	7,  // 19: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.CreateBook:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.CreateBookResponse
	9,  // 20: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.GetBook:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.GetBookResponse
	11, // 21: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.BorrowBook:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.BorrowBookResponse
	13, // 22: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.ReturnBook:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.ReturnBookResponse
	15, // 23: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.CreateShelf:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.CreateShelfResponse
	17, // 24: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.AddBookToShelf:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.AddBookToShelfResponse
	19, // 25: codesjoy.yggdrasil.example.proto.errorhandling.LibraryService.TriggerError:output_type -> codesjoy.yggdrasil.example.proto.errorhandling.TriggerErrorResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_error_handling_service_proto_init() }
func file_error_handling_service_proto_init() {
	if File_error_handling_service_proto != nil {
		return
	}
	file_error_handling_reason_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_handling_service_proto_rawDesc), len(file_error_handling_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_error_handling_service_proto_goTypes,
		DependencyIndexes: file_error_handling_service_proto_depIdxs,
		MessageInfos:      file_error_handling_service_proto_msgTypes,
	}.Build()
	File_error_handling_service_proto = out.File
	file_error_handling_service_proto_goTypes = nil
	file_error_handling_service_proto_depIdxs = nil
}
