// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package error_handling

import (
	context "context"
	xerror "github.com/codesjoy/pkg/basic/xerror"
	client "github.com/codesjoy/yggdrasil/v2/client"
	interceptor "github.com/codesjoy/yggdrasil/v2/interceptor"
	metadata "github.com/codesjoy/yggdrasil/v2/metadata"
	server "github.com/codesjoy/yggdrasil/v2/server"
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.
var _ = new(metadata.MD)

type LibraryServiceClient interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	BorrowBook(context.Context, *BorrowBookRequest) (*BorrowBookResponse, error)
	ReturnBook(context.Context, *ReturnBookRequest) (*ReturnBookResponse, error)
	CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error)
	AddBookToShelf(context.Context, *AddBookToShelfRequest) (*AddBookToShelfResponse, error)
	TriggerError(context.Context, *TriggerErrorRequest) (*TriggerErrorResponse, error)
}

type libraryserviceClient struct {
	cc client.Client
}

func NewLibraryServiceClient(cc client.Client) LibraryServiceClient {
	return &libraryserviceClient{cc}
}

func (c *libraryserviceClient) CreateUser(ctx context.Context, in *CreateUserRequest) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/CreateUser", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) GetUser(ctx context.Context, in *GetUserRequest) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/GetUser", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest) (*AuthenticateUserResponse, error) {
	out := new(AuthenticateUserResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/AuthenticateUser", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) CreateBook(ctx context.Context, in *CreateBookRequest) (*CreateBookResponse, error) {
	out := new(CreateBookResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/CreateBook", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) GetBook(ctx context.Context, in *GetBookRequest) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/GetBook", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) BorrowBook(ctx context.Context, in *BorrowBookRequest) (*BorrowBookResponse, error) {
	out := new(BorrowBookResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/BorrowBook", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) ReturnBook(ctx context.Context, in *ReturnBookRequest) (*ReturnBookResponse, error) {
	out := new(ReturnBookResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/ReturnBook", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) CreateShelf(ctx context.Context, in *CreateShelfRequest) (*CreateShelfResponse, error) {
	out := new(CreateShelfResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/CreateShelf", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) AddBookToShelf(ctx context.Context, in *AddBookToShelfRequest) (*AddBookToShelfResponse, error) {
	out := new(AddBookToShelfResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/AddBookToShelf", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryserviceClient) TriggerError(ctx context.Context, in *TriggerErrorRequest) (*TriggerErrorResponse, error) {
	out := new(TriggerErrorResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/TriggerError", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _LibraryService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).CreateUser(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).GetUser(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).AuthenticateUser(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/AuthenticateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).CreateBook(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).GetBook(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_BorrowBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).BorrowBook(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/BorrowBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).BorrowBook(ctx, req.(*BorrowBookRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_ReturnBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).ReturnBook(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/ReturnBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).ReturnBook(ctx, req.(*ReturnBookRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_CreateShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).CreateShelf(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/CreateShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).CreateShelf(ctx, req.(*CreateShelfRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_AddBookToShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookToShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).AddBookToShelf(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/AddBookToShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).AddBookToShelf(ctx, req.(*AddBookToShelfRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _LibraryService_TriggerError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(LibraryServiceServer).TriggerError(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.errorhandling.LibraryService/TriggerError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).TriggerError(ctx, req.(*TriggerErrorRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

type LibraryServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	BorrowBook(context.Context, *BorrowBookRequest) (*BorrowBookResponse, error)
	ReturnBook(context.Context, *ReturnBookRequest) (*ReturnBookResponse, error)
	CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error)
	AddBookToShelf(context.Context, *AddBookToShelfRequest) (*AddBookToShelfResponse, error)
	TriggerError(context.Context, *TriggerErrorRequest) (*TriggerErrorResponse, error)
	UnsafeLibraryServiceServer
}

type UnsafeLibraryServiceServer interface {
	mustEmbedUnimplementedLibraryServiceServer()
}

// UnimplementedLibraryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLibraryServiceServer struct {
}

func (UnimplementedLibraryServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method CreateUser not implemented")
}

func (UnimplementedLibraryServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method GetUser not implemented")
}

func (UnimplementedLibraryServiceServer) AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method AuthenticateUser not implemented")
}

func (UnimplementedLibraryServiceServer) CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method CreateBook not implemented")
}

func (UnimplementedLibraryServiceServer) GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method GetBook not implemented")
}

func (UnimplementedLibraryServiceServer) BorrowBook(context.Context, *BorrowBookRequest) (*BorrowBookResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method BorrowBook not implemented")
}

func (UnimplementedLibraryServiceServer) ReturnBook(context.Context, *ReturnBookRequest) (*ReturnBookResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method ReturnBook not implemented")
}

func (UnimplementedLibraryServiceServer) CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method CreateShelf not implemented")
}

func (UnimplementedLibraryServiceServer) AddBookToShelf(context.Context, *AddBookToShelfRequest) (*AddBookToShelfResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method AddBookToShelf not implemented")
}

func (UnimplementedLibraryServiceServer) TriggerError(context.Context, *TriggerErrorRequest) (*TriggerErrorResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method TriggerError not implemented")
}

func (UnimplementedLibraryServiceServer) mustEmbedUnimplementedLibraryServiceServer() {}

var LibraryServiceServiceDesc = server.ServiceDesc{
	ServiceName: "codesjoy.yggdrasil.example.proto.errorhandling.LibraryService",
	HandlerType: (*LibraryServiceServer)(nil),
	Methods: []server.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _LibraryService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _LibraryService_GetUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _LibraryService_AuthenticateUser_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _LibraryService_CreateBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _LibraryService_GetBook_Handler,
		},
		{
			MethodName: "BorrowBook",
			Handler:    _LibraryService_BorrowBook_Handler,
		},
		{
			MethodName: "ReturnBook",
			Handler:    _LibraryService_ReturnBook_Handler,
		},
		{
			MethodName: "CreateShelf",
			Handler:    _LibraryService_CreateShelf_Handler,
		},
		{
			MethodName: "AddBookToShelf",
			Handler:    _LibraryService_AddBookToShelf_Handler,
		},
		{
			MethodName: "TriggerError",
			Handler:    _LibraryService_TriggerError_Handler,
		},
	},
	Metadata: "error-handling/service.proto",
}
