// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package user_v1

import (
	context "context"
	xerror "github.com/codesjoy/pkg/basic/xerror"
	interceptor "github.com/codesjoy/yggdrasil/v3/rpc/interceptor"
	metadata "github.com/codesjoy/yggdrasil/v3/rpc/metadata"
	stream "github.com/codesjoy/yggdrasil/v3/rpc/stream"
	client "github.com/codesjoy/yggdrasil/v3/transport/runtime/client"
	server "github.com/codesjoy/yggdrasil/v3/transport/runtime/server"
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.
var _ = new(metadata.MD)

type UserServiceClient interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	ImportUsers(context.Context) (UserServiceImportUsersClient, error)
}

type UserServiceImportUsersClient interface {
	Send(*CreateUserRequest) error
	CloseAndRecv() (*ImportUsersResponse, error)
	stream.ClientStream
}

type userserviceClient struct {
	cc client.Client
}

func NewUserServiceClient(cc client.Client) UserServiceClient {
	return &userserviceClient{cc}
}

func (c *userserviceClient) CreateUser(ctx context.Context, in *CreateUserRequest) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.ecosystem.protovalidate.examples.user.v1.UserService/CreateUser", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userserviceClient) ImportUsers(ctx context.Context) (UserServiceImportUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserServiceServiceDesc.Streams[0], "/codesjoy.yggdrasil.ecosystem.protovalidate.examples.user.v1.UserService/ImportUsers")
	if err != nil {
		return nil, err
	}
	x := &userserviceImportUsersClient{stream}
	return x, nil
}

type userserviceImportUsersClient struct {
	stream.ClientStream
}

func (x *userserviceImportUsersClient) CloseAndRecv() (*ImportUsersResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImportUsersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *userserviceImportUsersClient) Header() (metadata.MD, error) {
	v, err := x.ClientStream.Header()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (x *userserviceImportUsersClient) Trailer() metadata.MD {
	return x.ClientStream.Trailer()
}

func (x *userserviceImportUsersClient) Send(m *CreateUserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.ecosystem.protovalidate.examples.user.v1.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _UserService_ImportUsers_Handler(srv interface{}, stream stream.ServerStream) error {
	return srv.(UserServiceServer).ImportUsers(&userserviceImportUsersServer{stream})
}

type userserviceImportUsersServer struct {
	stream.ServerStream
}

func (x *userserviceImportUsersServer) SetHeader(md metadata.MD) error {
	return x.ServerStream.SetHeader(md)
}

func (x *userserviceImportUsersServer) SendHeader(md metadata.MD) error {
	return x.ServerStream.SendHeader(md)
}

func (x *userserviceImportUsersServer) SetTrailer(md metadata.MD) {
	x.ServerStream.SetTrailer(md)
}

func (x *userserviceImportUsersServer) Context() context.Context {
	return x.ServerStream.Context()
}

func (x *userserviceImportUsersServer) SendAndClose(m *ImportUsersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userserviceImportUsersServer) Recv() (*CreateUserRequest, error) {
	m := new(CreateUserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	ImportUsers(UserServiceImportUsersServer) error
	UnsafeUserServiceServer
}

type UserServiceImportUsersServer interface {
	SendAndClose(*ImportUsersResponse) error
	Recv() (*CreateUserRequest, error)
	stream.ServerStream
}

type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method CreateUser not implemented")
}

func (UnimplementedUserServiceServer) ImportUsers(UserServiceImportUsersServer) error {
	return xerror.New(code.Code_UNIMPLEMENTED, "method ImportUsers not implemented")
}

func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

var UserServiceServiceDesc = server.ServiceDesc{
	ServiceName: "codesjoy.yggdrasil.ecosystem.protovalidate.examples.user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []server.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams: []stream.Desc{
		{
			StreamName:    "ImportUsers",
			Handler:       _UserService_ImportUsers_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "user/v1/user.proto",
}
