yggdrasil:
  etcd:
    clients:
      default:
        endpoints:
          - "127.0.0.1:2379"
        dial_timeout: 5s

  discovery:
    registry:
      type: etcd
      config:
        client: default
        prefix: /yggdrasil/registry
        ttl: 5s
        keep_alive: true
        retry_interval: 1s
    resolvers:
      default:
        type: etcd
        config:
          client: default
          prefix: /yggdrasil/registry
          namespace: default
          protocols: [grpc, http]
          debounce: 200ms
