yggdrasil:
  etcd:
    clients:
      default:
        endpoints:
          - "127.0.0.1:2379"
        dial_timeout: 5s

  config:
    sources:
      - kind: etcd
        name: etcd:kv
        priority: remote
        config:
          client: default
          prefix: /examples/etcd/kv
          watch: true
          format: yaml

app:
  config_source:
    greeting: "hello from local kv fallback"
    name: local
