yggdrasil:
  mode: dev
  server:
    transports:
      - grpc
  transports:
    grpc:
      server:
        address: "127.0.0.1:56092"

app:
  example:
    service: greeter
    greeting: hello from xDS multi-service
    instance: greeter
