apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
stringData:
  config.yaml: |
    app:
      config_source:
        greeting: "hello from Secret v2"
        name: remote-updated
