services:
  polaris:
    image: polarismesh/polaris-standalone:latest
    container_name: yggdrasil-polaris-quickstart
    ports:
      - "8080:8080"
      - "8090:8090"
      - "8091:8091"
      - "8093:8093"
      - "15010:15010"
      - "8761:8761"
      - "9000:9000"
      - "9090:9090"
    restart: unless-stopped
