// Copyright 2022 The codesjoy Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: helloworld/helloworld.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_helloworld_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayErrorRequest) Reset() {
	*x = SayErrorRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayErrorRequest) ProtoMessage() {}

func (x *SayErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayErrorRequest.ProtoReflect.Descriptor instead.
func (*SayErrorRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{2}
}

func (x *SayErrorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayErrorResponse) Reset() {
	*x = SayErrorResponse{}
	mi := &file_helloworld_helloworld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayErrorResponse) ProtoMessage() {}

func (x *SayErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayErrorResponse.ProtoReflect.Descriptor instead.
func (*SayErrorResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{3}
}

func (x *SayErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayHelloStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloStreamRequest) Reset() {
	*x = SayHelloStreamRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloStreamRequest) ProtoMessage() {}

func (x *SayHelloStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloStreamRequest.ProtoReflect.Descriptor instead.
func (*SayHelloStreamRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{4}
}

func (x *SayHelloStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloStreamResponse) Reset() {
	*x = SayHelloStreamResponse{}
	mi := &file_helloworld_helloworld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloStreamResponse) ProtoMessage() {}

func (x *SayHelloStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloStreamResponse.ProtoReflect.Descriptor instead.
func (*SayHelloStreamResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{5}
}

func (x *SayHelloStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayHelloClientStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloClientStreamRequest) Reset() {
	*x = SayHelloClientStreamRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloClientStreamRequest) ProtoMessage() {}

func (x *SayHelloClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloClientStreamRequest.ProtoReflect.Descriptor instead.
func (*SayHelloClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{6}
}

func (x *SayHelloClientStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloClientStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloClientStreamResponse) Reset() {
	*x = SayHelloClientStreamResponse{}
	mi := &file_helloworld_helloworld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloClientStreamResponse) ProtoMessage() {}

func (x *SayHelloClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloClientStreamResponse.ProtoReflect.Descriptor instead.
func (*SayHelloClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{7}
}

func (x *SayHelloClientStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayHelloServerStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloServerStreamRequest) Reset() {
	*x = SayHelloServerStreamRequest{}
	mi := &file_helloworld_helloworld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloServerStreamRequest) ProtoMessage() {}

func (x *SayHelloServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloServerStreamRequest.ProtoReflect.Descriptor instead.
func (*SayHelloServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{8}
}

func (x *SayHelloServerStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloServerStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloServerStreamResponse) Reset() {
	*x = SayHelloServerStreamResponse{}
	mi := &file_helloworld_helloworld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloServerStreamResponse) ProtoMessage() {}

func (x *SayHelloServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_helloworld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloServerStreamResponse.ProtoReflect.Descriptor instead.
func (*SayHelloServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_helloworld_proto_rawDescGZIP(), []int{9}
}

func (x *SayHelloServerStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_helloworld_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/helloworld.proto\x12*codesjoy.yggdrasil.example.proto.helloword\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x0fSayErrorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x15SayHelloStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x16SayHelloStreamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x1bSayHelloClientStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x1cSayHelloClientStreamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x1bSayHelloServerStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x1cSayHelloServerStreamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa4\x06\n" +
	"\x0eGreeterService\x12\x87\x01\n" +
	"\bSayHello\x12;.codesjoy.yggdrasil.example.proto.helloword.SayHelloRequest\x1a<.codesjoy.yggdrasil.example.proto.helloword.SayHelloResponse\"\x00\x12\x87\x01\n" +
	"\bSayError\x12;.codesjoy.yggdrasil.example.proto.helloword.SayErrorRequest\x1a<.codesjoy.yggdrasil.example.proto.helloword.SayErrorResponse\"\x00\x12\x9d\x01\n" +
	"\x0eSayHelloStream\x12A.codesjoy.yggdrasil.example.proto.helloword.SayHelloStreamRequest\x1aB.codesjoy.yggdrasil.example.proto.helloword.SayHelloStreamResponse\"\x00(\x010\x01\x12\xad\x01\n" +
	"\x14SayHelloClientStream\x12G.codesjoy.yggdrasil.example.proto.helloword.SayHelloClientStreamRequest\x1aH.codesjoy.yggdrasil.example.proto.helloword.SayHelloClientStreamResponse\"\x00(\x01\x12\xad\x01\n" +
	"\x14SayHelloServerStream\x12G.codesjoy.yggdrasil.example.proto.helloword.SayHelloServerStreamRequest\x1aH.codesjoy.yggdrasil.example.proto.helloword.SayHelloServerStreamResponse\"\x000\x01B\xa6\x02\n" +
	".com.codesjoy.yggdrasil.example.proto.hellowordB\x0fHelloworldProtoP\x01Z\x15github.com/helloworld\xa2\x02\x05CYEPH\xaa\x02*Codesjoy.Yggdrasil.Example.Proto.Helloword\xca\x02*Codesjoy\\Yggdrasil\\Example\\Proto\\Helloword\xe2\x026Codesjoy\\Yggdrasil\\Example\\Proto\\Helloword\\GPBMetadata\xea\x02.Codesjoy::Yggdrasil::Example::Proto::Hellowordb\x06proto3"

var (
	file_helloworld_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_helloworld_proto_rawDescData []byte
)

func file_helloworld_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_helloworld_proto_rawDesc), len(file_helloworld_helloworld_proto_rawDesc)))
	})
	return file_helloworld_helloworld_proto_rawDescData
}

var file_helloworld_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_helloworld_helloworld_proto_goTypes = []any{
	(*SayHelloRequest)(nil),              // 0: codesjoy.yggdrasil.example.proto.helloword.SayHelloRequest
	(*SayHelloResponse)(nil),             // 1: codesjoy.yggdrasil.example.proto.helloword.SayHelloResponse
	(*SayErrorRequest)(nil),              // 2: codesjoy.yggdrasil.example.proto.helloword.SayErrorRequest
	(*SayErrorResponse)(nil),             // 3: codesjoy.yggdrasil.example.proto.helloword.SayErrorResponse
	(*SayHelloStreamRequest)(nil),        // 4: codesjoy.yggdrasil.example.proto.helloword.SayHelloStreamRequest
	(*SayHelloStreamResponse)(nil),       // 5: codesjoy.yggdrasil.example.proto.helloword.SayHelloStreamResponse
	(*SayHelloClientStreamRequest)(nil),  // 6: codesjoy.yggdrasil.example.proto.helloword.SayHelloClientStreamRequest
	(*SayHelloClientStreamResponse)(nil), // 7: codesjoy.yggdrasil.example.proto.helloword.SayHelloClientStreamResponse
	(*SayHelloServerStreamRequest)(nil),  // 8: codesjoy.yggdrasil.example.proto.helloword.SayHelloServerStreamRequest
	(*SayHelloServerStreamResponse)(nil), // 9: codesjoy.yggdrasil.example.proto.helloword.SayHelloServerStreamResponse
}
var file_helloworld_helloworld_proto_depIdxs = []int32{
	0, // 0: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHello:input_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloRequest
	2, // 1: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayError:input_type -> codesjoy.yggdrasil.example.proto.helloword.SayErrorRequest
	4, // 2: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHelloStream:input_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloStreamRequest
	6, // 3: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHelloClientStream:input_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloClientStreamRequest
	8, // 4: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHelloServerStream:input_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloServerStreamRequest
	1, // 5: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHello:output_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloResponse
	3, // 6: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayError:output_type -> codesjoy.yggdrasil.example.proto.helloword.SayErrorResponse
	5, // 7: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHelloStream:output_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloStreamResponse
	7, // 8: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHelloClientStream:output_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloClientStreamResponse
	9, // 9: codesjoy.yggdrasil.example.proto.helloword.GreeterService.SayHelloServerStream:output_type -> codesjoy.yggdrasil.example.proto.helloword.SayHelloServerStreamResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_helloworld_proto_init() }
func file_helloworld_helloworld_proto_init() {
	if File_helloworld_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_helloworld_proto_rawDesc), len(file_helloworld_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_helloworld_proto_depIdxs,
		MessageInfos:      file_helloworld_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_helloworld_proto = out.File
	file_helloworld_helloworld_proto_goTypes = nil
	file_helloworld_helloworld_proto_depIdxs = nil
}
