// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	xerror "github.com/codesjoy/pkg/basic/xerror"
	client "github.com/codesjoy/yggdrasil/v2/client"
	interceptor "github.com/codesjoy/yggdrasil/v2/interceptor"
	metadata "github.com/codesjoy/yggdrasil/v2/metadata"
	server "github.com/codesjoy/yggdrasil/v2/server"
	stream "github.com/codesjoy/yggdrasil/v2/stream"
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.
var _ = new(metadata.MD)

type GreeterServiceClient interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	SayError(context.Context, *SayErrorRequest) (*SayErrorResponse, error)
	SayHelloStream(context.Context) (GreeterServiceSayHelloStreamClient, error)
	SayHelloClientStream(context.Context) (GreeterServiceSayHelloClientStreamClient, error)
	SayHelloServerStream(context.Context, *SayHelloServerStreamRequest) (GreeterServiceSayHelloServerStreamClient, error)
}

type GreeterServiceSayHelloStreamClient interface {
	Send(*SayHelloStreamRequest) error
	Recv() (*SayHelloStreamResponse, error)
	stream.ClientStream
}

type GreeterServiceSayHelloClientStreamClient interface {
	Send(*SayHelloClientStreamRequest) error
	stream.ClientStream
}

type GreeterServiceSayHelloServerStreamClient interface {
	CloseAndRecv() (*SayHelloServerStreamResponse, error)
	Recv() (*SayHelloServerStreamResponse, error)
	stream.ClientStream
}

type greeterserviceClient struct {
	cc client.Client
}

func NewGreeterServiceClient(cc client.Client) GreeterServiceClient {
	return &greeterserviceClient{cc}
}

func (c *greeterserviceClient) SayHello(ctx context.Context, in *SayHelloRequest) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayHello", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterserviceClient) SayError(ctx context.Context, in *SayErrorRequest) (*SayErrorResponse, error) {
	out := new(SayErrorResponse)
	err := c.cc.Invoke(ctx, "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayError", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterserviceClient) SayHelloStream(ctx context.Context) (GreeterServiceSayHelloStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterServiceServiceDesc.Streams[0], "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayHelloStream")
	if err != nil {
		return nil, err
	}
	x := &greeterserviceSayHelloStreamClient{stream}
	return x, nil
}

type greeterserviceSayHelloStreamClient struct {
	stream.ClientStream
}

func (x *greeterserviceSayHelloStreamClient) Header() (metadata.MD, error) {
	v, err := x.ClientStream.Header()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (x *greeterserviceSayHelloStreamClient) Trailer() metadata.MD {
	return x.ClientStream.Trailer()
}

func (x *greeterserviceSayHelloStreamClient) Send(m *SayHelloStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterserviceSayHelloStreamClient) Recv() (*SayHelloStreamResponse, error) {
	m := new(SayHelloStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
func (c *greeterserviceClient) SayHelloClientStream(ctx context.Context) (GreeterServiceSayHelloClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterServiceServiceDesc.Streams[1], "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayHelloClientStream")
	if err != nil {
		return nil, err
	}
	x := &greeterserviceSayHelloClientStreamClient{stream}
	return x, nil
}

type greeterserviceSayHelloClientStreamClient struct {
	stream.ClientStream
}

func (x *greeterserviceSayHelloClientStreamClient) Header() (metadata.MD, error) {
	v, err := x.ClientStream.Header()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (x *greeterserviceSayHelloClientStreamClient) Trailer() metadata.MD {
	return x.ClientStream.Trailer()
}

func (x *greeterserviceSayHelloClientStreamClient) Send(m *SayHelloClientStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (c *greeterserviceClient) SayHelloServerStream(ctx context.Context, in *SayHelloServerStreamRequest) (GreeterServiceSayHelloServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreeterServiceServiceDesc.Streams[2], "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayHelloServerStream")
	if err != nil {
		return nil, err
	}
	x := &greeterserviceSayHelloServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type greeterserviceSayHelloServerStreamClient struct {
	stream.ClientStream
}

func (x *greeterserviceSayHelloServerStreamClient) CloseAndRecv() (*SayHelloServerStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SayHelloServerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *greeterserviceSayHelloServerStreamClient) Recv() (*SayHelloServerStreamResponse, error) {
	m := new(SayHelloServerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *greeterserviceSayHelloServerStreamClient) Header() (metadata.MD, error) {
	v, err := x.ClientStream.Header()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (x *greeterserviceSayHelloServerStreamClient) Trailer() metadata.MD {
	return x.ClientStream.Trailer()
}

func (x *greeterserviceSayHelloServerStreamClient) Send(m *SayHelloServerStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func _GreeterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(GreeterServiceServer).SayHello(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _GreeterService_SayError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, unaryInt interceptor.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if unaryInt == nil {
		return srv.(GreeterServiceServer).SayError(ctx, in)
	}
	info := &interceptor.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codesjoy.yggdrasil.example.proto.helloword.GreeterService/SayError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayError(ctx, req.(*SayErrorRequest))
	}
	return unaryInt(ctx, in, info, handler)
}

func _GreeterService_SayHelloStream_Handler(srv interface{}, stream stream.ServerStream) error {
	return srv.(GreeterServiceServer).SayHelloStream(&greeterserviceSayHelloStreamServer{stream})
}

type greeterserviceSayHelloStreamServer struct {
	stream.ServerStream
}

func (x *greeterserviceSayHelloStreamServer) SetHeader(md metadata.MD) error {
	return x.ServerStream.SetHeader(md)
}

func (x *greeterserviceSayHelloStreamServer) SendHeader(md metadata.MD) error {
	return x.ServerStream.SendHeader(md)
}

func (x *greeterserviceSayHelloStreamServer) SetTrailer(md metadata.MD) {
	x.ServerStream.SetTrailer(md)
}

func (x *greeterserviceSayHelloStreamServer) Context() context.Context {
	return x.ServerStream.Context()
}

func (x *greeterserviceSayHelloStreamServer) Send(m *SayHelloStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterserviceSayHelloStreamServer) Recv() (*SayHelloStreamRequest, error) {
	m := new(SayHelloStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreeterService_SayHelloClientStream_Handler(srv interface{}, stream stream.ServerStream) error {
	return srv.(GreeterServiceServer).SayHelloClientStream(&greeterserviceSayHelloClientStreamServer{stream})
}

type greeterserviceSayHelloClientStreamServer struct {
	stream.ServerStream
}

func (x *greeterserviceSayHelloClientStreamServer) SetHeader(md metadata.MD) error {
	return x.ServerStream.SetHeader(md)
}

func (x *greeterserviceSayHelloClientStreamServer) SendHeader(md metadata.MD) error {
	return x.ServerStream.SendHeader(md)
}

func (x *greeterserviceSayHelloClientStreamServer) SetTrailer(md metadata.MD) {
	x.ServerStream.SetTrailer(md)
}

func (x *greeterserviceSayHelloClientStreamServer) Context() context.Context {
	return x.ServerStream.Context()
}

func (x *greeterserviceSayHelloClientStreamServer) SendAndClose(m *SayHelloClientStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterserviceSayHelloClientStreamServer) Recv() (*SayHelloClientStreamRequest, error) {
	m := new(SayHelloClientStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreeterService_SayHelloServerStream_Handler(srv interface{}, stream stream.ServerStream) error {
	m := new(SayHelloServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).SayHelloServerStream(m, &greeterserviceSayHelloServerStreamServer{stream})
}

type greeterserviceSayHelloServerStreamServer struct {
	stream.ServerStream
}

func (x *greeterserviceSayHelloServerStreamServer) SetHeader(md metadata.MD) error {
	return x.ServerStream.SetHeader(md)
}

func (x *greeterserviceSayHelloServerStreamServer) SendHeader(md metadata.MD) error {
	return x.ServerStream.SendHeader(md)
}

func (x *greeterserviceSayHelloServerStreamServer) SetTrailer(md metadata.MD) {
	x.ServerStream.SetTrailer(md)
}

func (x *greeterserviceSayHelloServerStreamServer) Context() context.Context {
	return x.ServerStream.Context()
}

func (x *greeterserviceSayHelloServerStreamServer) Send(m *SayHelloServerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

type GreeterServiceServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	SayError(context.Context, *SayErrorRequest) (*SayErrorResponse, error)
	SayHelloStream(GreeterServiceSayHelloStreamServer) error
	SayHelloClientStream(GreeterServiceSayHelloClientStreamServer) error
	SayHelloServerStream(*SayHelloServerStreamRequest, GreeterServiceSayHelloServerStreamServer) error
	UnsafeGreeterServiceServer
}

type GreeterServiceSayHelloStreamServer interface {
	Send(*SayHelloStreamResponse) error
	Recv() (*SayHelloStreamRequest, error)
	stream.ServerStream
}

type GreeterServiceSayHelloClientStreamServer interface {
	SendAndClose(*SayHelloClientStreamResponse) error
	Recv() (*SayHelloClientStreamRequest, error)
	stream.ServerStream
}

type GreeterServiceSayHelloServerStreamServer interface {
	Send(*SayHelloServerStreamResponse) error
	stream.ServerStream
}

type UnsafeGreeterServiceServer interface {
	mustEmbedUnimplementedGreeterServiceServer()
}

// UnimplementedGreeterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServiceServer struct {
}

func (UnimplementedGreeterServiceServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method SayHello not implemented")
}

func (UnimplementedGreeterServiceServer) SayError(context.Context, *SayErrorRequest) (*SayErrorResponse, error) {
	return nil, xerror.New(code.Code_UNIMPLEMENTED, "method SayError not implemented")
}

func (UnimplementedGreeterServiceServer) SayHelloStream(GreeterServiceSayHelloStreamServer) error {
	return xerror.New(code.Code_UNIMPLEMENTED, "method SayHelloStream not implemented")
}

func (UnimplementedGreeterServiceServer) SayHelloClientStream(GreeterServiceSayHelloClientStreamServer) error {
	return xerror.New(code.Code_UNIMPLEMENTED, "method SayHelloClientStream not implemented")
}

func (UnimplementedGreeterServiceServer) SayHelloServerStream(*SayHelloServerStreamRequest, GreeterServiceSayHelloServerStreamServer) error {
	return xerror.New(code.Code_UNIMPLEMENTED, "method SayHelloServerStream not implemented")
}

func (UnimplementedGreeterServiceServer) mustEmbedUnimplementedGreeterServiceServer() {}

var GreeterServiceServiceDesc = server.ServiceDesc{
	ServiceName: "codesjoy.yggdrasil.example.proto.helloword.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []server.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreeterService_SayHello_Handler,
		},
		{
			MethodName: "SayError",
			Handler:    _GreeterService_SayError_Handler,
		},
	},
	Streams: []stream.Desc{
		{
			StreamName:    "SayHelloStream",
			Handler:       _GreeterService_SayHelloStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloClientStream",
			Handler:       _GreeterService_SayHelloClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloServerStream",
			Handler:       _GreeterService_SayHelloServerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helloworld/helloworld.proto",
}
