yggdrasil:
  mode: dev
  discovery:
    resolvers:
      xds:
        type: xds
        config:
          name: default
  balancers:
    defaults:
      xds:
        type: xds
        config: {}
  clients:
    services:
      sample:
        resolver: xds
        balancer: xds
  xds:
    default:
      config:
        server:
          address: "127.0.0.1:18000"
          timeout: 5s
        node:
          id: "traffic-splitting-canary-client"
          cluster: "xds-examples"
        protocol: grpc

app:
  example:
    services:
      - sample
    requests: 3
    name: split-canary
    headers:
      x-release: canary
