yggdrasil:
  mode: dev
  server:
    transports:
      - grpc
  transports:
    grpc:
      server:
        address: "127.0.0.1:56081"

app:
  example:
    service: sample
    greeting: hello from xDS traffic splitting
    instance: stable
